/**
 * An abstract class representing Root type Crops.
 * Does not have any special multipliers or conditions.
 */
public abstract class RootCrop extends Crop {
    /**
     * Constructor for Root type Crops. Parameters define the values of the Root Crop
     * 
     * @param name name of the root crop
     * @param id character id of the root crop
     * @param harvestTime days required before the root crop can be harvested
     * @param water required water level for the root crop
     * @param fertilizer required fertilizer level for the root crop
     * @param prodMax maximum amount of produce generated by the root crop
     * @param seedCost cost of planting the root crop
     * @param sellPrice sell price of produce made by the root crop
     * @param xp experience yield from harvesting the root crop
     */
    public RootCrop(String name, char id, int harvestTime, int water, int fertilizer, int prodMax,
                    int seedCost, int sellPrice, double xp){
        super(name, id, harvestTime, water, fertilizer, 1, 1, prodMax, seedCost, sellPrice, xp);
    }
}
