/**
 * An abstract class representing Tree type Crops.
 * Can not be planted next to occupied tiles or in edges and corners.
 */
public abstract class Tree extends Crop {
    /**
     * Constructor for Tree type Crops
     * 
     * @param name name of the tree crop
     * @param id character id of the tree crop
     * @param fertilizer required fertilizer of the tree crop
     * @param prodMin minimum amount of produce generated by the tree crop
     * @param seedCost cost of planting the tree crop
     * @param sellPrice sepp price of produce made by the tree crop
     */
    public Tree(String name, char id, int fertilizer, int prodMin, int seedCost, int sellPrice){
        super(name, id, 10, 7, fertilizer, 0, prodMin, 15, seedCost, sellPrice, 25);
    }
}
